[package]
name        = "swe_justpkg_config"
version     = "0.1.0"
edition     = "2021"
description = "Application configuration loader (XDG) for justpkg tools"

[dependencies]
edge-configbuilder = { workspace = true }
serde              = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
