[package]
name        = "swe_justpkg_cli"
version     = "0.1.0"
edition.workspace      = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true
authors.workspace      = true
rust-version.workspace = true
description = "justpkg — Nix NAR fetcher and extractor CLI"

[[bin]]
name = "pkg"
path = "src/main.rs"

[dependencies]
edge-domain     = { workspace = true }
justpkg-pkg     = { workspace = true }
justpkg-nix     = { workspace = true }
justpkg-config  = { workspace = true }
justpkg-resolve = { workspace = true }
justpkg-vminit  = { workspace = true }
justpkg-rootfs  = { workspace = true }
cas        = { workspace = true }
ext4       = { workspace = true }
clap       = { workspace = true }
serde_json = { workspace = true }
toml       = { workspace = true }
tempfile   = { workspace = true }
dirs-next  = "2"
