[package]
name        = "swe_justpkg_rootfs"
version     = "0.1.0"
edition.workspace      = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true
authors.workspace      = true
rust-version.workspace = true
description = "justpkg rootfs builder — TOML-driven ext4 image pipeline"

[dependencies]
edge-domain     = { workspace = true }
ext4            = { workspace = true }
justpkg-config  = { workspace = true }
justpkg-resolve = { workspace = true }
justpkg-vminit  = { workspace = true }
justpkg-pkg     = { workspace = true }
tempfile        = { workspace = true }

[dev-dependencies]
toml     = { workspace = true }
tempfile = { workspace = true }
